/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminRouteRouteImport } from './routes/admin/route';
import { Route as SignInRouteImport } from './routes/sign-in';
import { Route as TenantAppRouteRouteImport } from './routes/$tenant/app/route';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as AdminAuditRouteImport } from './routes/admin/audit';
import { Route as AdminPrincipalsRouteImport } from './routes/admin/principals';
import { Route as AdminSettingsRouteImport } from './routes/admin/settings';
import { Route as AdminUsageRouteImport } from './routes/admin/usage';
import { Route as TenantAppIndexRouteImport } from './routes/$tenant/app/index';
import { Route as TenantAppEirRouteRouteImport } from './routes/$tenant/app/eir/route';
import { Route as TenantAppProgramRouteRouteImport } from './routes/$tenant/app/program/route';
import { Route as TenantAppEirIndexRouteImport } from './routes/$tenant/app/eir/index';
import { Route as TenantAppEirInboxRouteImport } from './routes/$tenant/app/eir/inbox';
import { Route as TenantAppEirReviewsRouteImport } from './routes/$tenant/app/eir/reviews';
import { Route as TenantAppProgramIndexRouteImport } from './routes/$tenant/app/program/index';
import { Route as TenantAppProgramEscalationsRouteImport } from './routes/$tenant/app/program/escalations';
import { Route as TenantAppProgramPortfolioRouteImport } from './routes/$tenant/app/program/portfolio';
import { Route as TenantAppProgramResourcesRouteImport } from './routes/$tenant/app/program/resources';
import { Route as TenantAppProgramVenturesRouteImport } from './routes/$tenant/app/program/ventures';
import { Route as TenantAppVenturesIndexRouteImport } from './routes/$tenant/app/ventures/index';
import { Route as TenantAppVenturesVentureIdRouteRouteImport } from './routes/$tenant/app/ventures/$ventureId/route';
import { Route as TenantAppEirPersonasIndexRouteImport } from './routes/$tenant/app/eir/personas/index';
import { Route as TenantAppEirPersonasPersonaIdRouteImport } from './routes/$tenant/app/eir/personas/$personaId';
import { Route as TenantAppVenturesVentureIdIndexRouteImport } from './routes/$tenant/app/ventures/$ventureId/index';
import { Route as TenantAppVenturesVentureIdDecisionsRouteImport } from './routes/$tenant/app/ventures/$ventureId/decisions';
import { Route as TenantAppVenturesVentureIdDocumentsRouteImport } from './routes/$tenant/app/ventures/$ventureId/documents';
import { Route as TenantAppVenturesVentureIdEscalationsRouteImport } from './routes/$tenant/app/ventures/$ventureId/escalations';
import { Route as TenantAppVenturesVentureIdEvidenceRouteImport } from './routes/$tenant/app/ventures/$ventureId/evidence';
import { Route as TenantAppVenturesVentureIdExperimentsRouteImport } from './routes/$tenant/app/ventures/$ventureId/experiments';
import { Route as TenantAppVenturesVentureIdMemoryRouteImport } from './routes/$tenant/app/ventures/$ventureId/memory';
import { Route as TenantAppVenturesVentureIdMilestonesRouteImport } from './routes/$tenant/app/ventures/$ventureId/milestones';
import { Route as TenantAppVenturesVentureIdOverviewRouteImport } from './routes/$tenant/app/ventures/$ventureId/overview';
import { Route as TenantAppVenturesVentureIdTeamRouteImport } from './routes/$tenant/app/ventures/$ventureId/team';
import { Route as TenantAppVenturesVentureIdCoachIndexRouteImport } from './routes/$tenant/app/ventures/$ventureId/coach/index';
import { Route as TenantAppVenturesVentureIdCoachSessionIdRouteImport } from './routes/$tenant/app/ventures/$ventureId/coach/$sessionId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any);
const TenantAppRouteRoute = TenantAppRouteRouteImport.update({
  id: '/$tenant/app',
  path: '/$tenant/app',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminPrincipalsRoute = AdminPrincipalsRouteImport.update({
  id: '/principals',
  path: '/principals',
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRouteRoute,
} as any);
const TenantAppIndexRoute = TenantAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppRouteRoute,
} as any);
const TenantAppEirRouteRoute = TenantAppEirRouteRouteImport.update({
  id: '/eir',
  path: '/eir',
  getParentRoute: () => TenantAppRouteRoute,
} as any);
const TenantAppProgramRouteRoute = TenantAppProgramRouteRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => TenantAppRouteRoute,
} as any);
const TenantAppEirIndexRoute = TenantAppEirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppEirRouteRoute,
} as any);
const TenantAppEirInboxRoute = TenantAppEirInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => TenantAppEirRouteRoute,
} as any);
const TenantAppEirReviewsRoute = TenantAppEirReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TenantAppEirRouteRoute,
} as any);
const TenantAppProgramIndexRoute = TenantAppProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAppProgramRouteRoute,
} as any);
const TenantAppProgramEscalationsRoute =
  TenantAppProgramEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => TenantAppProgramRouteRoute,
  } as any);
const TenantAppProgramPortfolioRoute =
  TenantAppProgramPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => TenantAppProgramRouteRoute,
  } as any);
const TenantAppProgramResourcesRoute =
  TenantAppProgramResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => TenantAppProgramRouteRoute,
  } as any);
const TenantAppProgramVenturesRoute =
  TenantAppProgramVenturesRouteImport.update({
    id: '/ventures',
    path: '/ventures',
    getParentRoute: () => TenantAppProgramRouteRoute,
  } as any);
const TenantAppVenturesIndexRoute = TenantAppVenturesIndexRouteImport.update({
  id: '/ventures/',
  path: '/ventures/',
  getParentRoute: () => TenantAppRouteRoute,
} as any);
const TenantAppVenturesVentureIdRouteRoute =
  TenantAppVenturesVentureIdRouteRouteImport.update({
    id: '/ventures/$ventureId',
    path: '/ventures/$ventureId',
    getParentRoute: () => TenantAppRouteRoute,
  } as any);
const TenantAppEirPersonasIndexRoute =
  TenantAppEirPersonasIndexRouteImport.update({
    id: '/personas/',
    path: '/personas/',
    getParentRoute: () => TenantAppEirRouteRoute,
  } as any);
const TenantAppEirPersonasPersonaIdRoute =
  TenantAppEirPersonasPersonaIdRouteImport.update({
    id: '/personas/$personaId',
    path: '/personas/$personaId',
    getParentRoute: () => TenantAppEirRouteRoute,
  } as any);
const TenantAppVenturesVentureIdIndexRoute =
  TenantAppVenturesVentureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdDecisionsRoute =
  TenantAppVenturesVentureIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdDocumentsRoute =
  TenantAppVenturesVentureIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdEscalationsRoute =
  TenantAppVenturesVentureIdEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdEvidenceRoute =
  TenantAppVenturesVentureIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdExperimentsRoute =
  TenantAppVenturesVentureIdExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdMemoryRoute =
  TenantAppVenturesVentureIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdMilestonesRoute =
  TenantAppVenturesVentureIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdOverviewRoute =
  TenantAppVenturesVentureIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdTeamRoute =
  TenantAppVenturesVentureIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdCoachIndexRoute =
  TenantAppVenturesVentureIdCoachIndexRouteImport.update({
    id: '/coach/',
    path: '/coach/',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);
const TenantAppVenturesVentureIdCoachSessionIdRoute =
  TenantAppVenturesVentureIdCoachSessionIdRouteImport.update({
    id: '/coach/$sessionId',
    path: '/coach/$sessionId',
    getParentRoute: () => TenantAppVenturesVentureIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteRouteWithChildren;
  '/sign-in': typeof SignInRoute;
  '/$tenant/app': typeof TenantAppRouteRouteWithChildren;
  '/admin/audit': typeof AdminAuditRoute;
  '/admin/principals': typeof AdminPrincipalsRoute;
  '/admin/settings': typeof AdminSettingsRoute;
  '/admin/usage': typeof AdminUsageRoute;
  '/admin/': typeof AdminIndexRoute;
  '/$tenant/app/eir': typeof TenantAppEirRouteRouteWithChildren;
  '/$tenant/app/program': typeof TenantAppProgramRouteRouteWithChildren;
  '/$tenant/app/': typeof TenantAppIndexRoute;
  '/$tenant/app/ventures/$ventureId': typeof TenantAppVenturesVentureIdRouteRouteWithChildren;
  '/$tenant/app/eir/inbox': typeof TenantAppEirInboxRoute;
  '/$tenant/app/eir/reviews': typeof TenantAppEirReviewsRoute;
  '/$tenant/app/program/escalations': typeof TenantAppProgramEscalationsRoute;
  '/$tenant/app/program/portfolio': typeof TenantAppProgramPortfolioRoute;
  '/$tenant/app/program/resources': typeof TenantAppProgramResourcesRoute;
  '/$tenant/app/program/ventures': typeof TenantAppProgramVenturesRoute;
  '/$tenant/app/eir/': typeof TenantAppEirIndexRoute;
  '/$tenant/app/program/': typeof TenantAppProgramIndexRoute;
  '/$tenant/app/ventures/': typeof TenantAppVenturesIndexRoute;
  '/$tenant/app/eir/personas/$personaId': typeof TenantAppEirPersonasPersonaIdRoute;
  '/$tenant/app/ventures/$ventureId/decisions': typeof TenantAppVenturesVentureIdDecisionsRoute;
  '/$tenant/app/ventures/$ventureId/documents': typeof TenantAppVenturesVentureIdDocumentsRoute;
  '/$tenant/app/ventures/$ventureId/escalations': typeof TenantAppVenturesVentureIdEscalationsRoute;
  '/$tenant/app/ventures/$ventureId/evidence': typeof TenantAppVenturesVentureIdEvidenceRoute;
  '/$tenant/app/ventures/$ventureId/experiments': typeof TenantAppVenturesVentureIdExperimentsRoute;
  '/$tenant/app/ventures/$ventureId/memory': typeof TenantAppVenturesVentureIdMemoryRoute;
  '/$tenant/app/ventures/$ventureId/milestones': typeof TenantAppVenturesVentureIdMilestonesRoute;
  '/$tenant/app/ventures/$ventureId/overview': typeof TenantAppVenturesVentureIdOverviewRoute;
  '/$tenant/app/ventures/$ventureId/team': typeof TenantAppVenturesVentureIdTeamRoute;
  '/$tenant/app/eir/personas/': typeof TenantAppEirPersonasIndexRoute;
  '/$tenant/app/ventures/$ventureId/': typeof TenantAppVenturesVentureIdIndexRoute;
  '/$tenant/app/ventures/$ventureId/coach/$sessionId': typeof TenantAppVenturesVentureIdCoachSessionIdRoute;
  '/$tenant/app/ventures/$ventureId/coach/': typeof TenantAppVenturesVentureIdCoachIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof SignInRoute;
  '/admin/audit': typeof AdminAuditRoute;
  '/admin/principals': typeof AdminPrincipalsRoute;
  '/admin/settings': typeof AdminSettingsRoute;
  '/admin/usage': typeof AdminUsageRoute;
  '/admin': typeof AdminIndexRoute;
  '/$tenant/app': typeof TenantAppIndexRoute;
  '/$tenant/app/eir/inbox': typeof TenantAppEirInboxRoute;
  '/$tenant/app/eir/reviews': typeof TenantAppEirReviewsRoute;
  '/$tenant/app/program/escalations': typeof TenantAppProgramEscalationsRoute;
  '/$tenant/app/program/portfolio': typeof TenantAppProgramPortfolioRoute;
  '/$tenant/app/program/resources': typeof TenantAppProgramResourcesRoute;
  '/$tenant/app/program/ventures': typeof TenantAppProgramVenturesRoute;
  '/$tenant/app/eir': typeof TenantAppEirIndexRoute;
  '/$tenant/app/program': typeof TenantAppProgramIndexRoute;
  '/$tenant/app/ventures': typeof TenantAppVenturesIndexRoute;
  '/$tenant/app/eir/personas/$personaId': typeof TenantAppEirPersonasPersonaIdRoute;
  '/$tenant/app/ventures/$ventureId/decisions': typeof TenantAppVenturesVentureIdDecisionsRoute;
  '/$tenant/app/ventures/$ventureId/documents': typeof TenantAppVenturesVentureIdDocumentsRoute;
  '/$tenant/app/ventures/$ventureId/escalations': typeof TenantAppVenturesVentureIdEscalationsRoute;
  '/$tenant/app/ventures/$ventureId/evidence': typeof TenantAppVenturesVentureIdEvidenceRoute;
  '/$tenant/app/ventures/$ventureId/experiments': typeof TenantAppVenturesVentureIdExperimentsRoute;
  '/$tenant/app/ventures/$ventureId/memory': typeof TenantAppVenturesVentureIdMemoryRoute;
  '/$tenant/app/ventures/$ventureId/milestones': typeof TenantAppVenturesVentureIdMilestonesRoute;
  '/$tenant/app/ventures/$ventureId/overview': typeof TenantAppVenturesVentureIdOverviewRoute;
  '/$tenant/app/ventures/$ventureId/team': typeof TenantAppVenturesVentureIdTeamRoute;
  '/$tenant/app/eir/personas': typeof TenantAppEirPersonasIndexRoute;
  '/$tenant/app/ventures/$ventureId': typeof TenantAppVenturesVentureIdIndexRoute;
  '/$tenant/app/ventures/$ventureId/coach/$sessionId': typeof TenantAppVenturesVentureIdCoachSessionIdRoute;
  '/$tenant/app/ventures/$ventureId/coach': typeof TenantAppVenturesVentureIdCoachIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteRouteWithChildren;
  '/sign-in': typeof SignInRoute;
  '/$tenant/app': typeof TenantAppRouteRouteWithChildren;
  '/admin/audit': typeof AdminAuditRoute;
  '/admin/principals': typeof AdminPrincipalsRoute;
  '/admin/settings': typeof AdminSettingsRoute;
  '/admin/usage': typeof AdminUsageRoute;
  '/admin/': typeof AdminIndexRoute;
  '/$tenant/app/eir': typeof TenantAppEirRouteRouteWithChildren;
  '/$tenant/app/program': typeof TenantAppProgramRouteRouteWithChildren;
  '/$tenant/app/': typeof TenantAppIndexRoute;
  '/$tenant/app/ventures/$ventureId': typeof TenantAppVenturesVentureIdRouteRouteWithChildren;
  '/$tenant/app/eir/inbox': typeof TenantAppEirInboxRoute;
  '/$tenant/app/eir/reviews': typeof TenantAppEirReviewsRoute;
  '/$tenant/app/program/escalations': typeof TenantAppProgramEscalationsRoute;
  '/$tenant/app/program/portfolio': typeof TenantAppProgramPortfolioRoute;
  '/$tenant/app/program/resources': typeof TenantAppProgramResourcesRoute;
  '/$tenant/app/program/ventures': typeof TenantAppProgramVenturesRoute;
  '/$tenant/app/eir/': typeof TenantAppEirIndexRoute;
  '/$tenant/app/program/': typeof TenantAppProgramIndexRoute;
  '/$tenant/app/ventures/': typeof TenantAppVenturesIndexRoute;
  '/$tenant/app/eir/personas/$personaId': typeof TenantAppEirPersonasPersonaIdRoute;
  '/$tenant/app/ventures/$ventureId/decisions': typeof TenantAppVenturesVentureIdDecisionsRoute;
  '/$tenant/app/ventures/$ventureId/documents': typeof TenantAppVenturesVentureIdDocumentsRoute;
  '/$tenant/app/ventures/$ventureId/escalations': typeof TenantAppVenturesVentureIdEscalationsRoute;
  '/$tenant/app/ventures/$ventureId/evidence': typeof TenantAppVenturesVentureIdEvidenceRoute;
  '/$tenant/app/ventures/$ventureId/experiments': typeof TenantAppVenturesVentureIdExperimentsRoute;
  '/$tenant/app/ventures/$ventureId/memory': typeof TenantAppVenturesVentureIdMemoryRoute;
  '/$tenant/app/ventures/$ventureId/milestones': typeof TenantAppVenturesVentureIdMilestonesRoute;
  '/$tenant/app/ventures/$ventureId/overview': typeof TenantAppVenturesVentureIdOverviewRoute;
  '/$tenant/app/ventures/$ventureId/team': typeof TenantAppVenturesVentureIdTeamRoute;
  '/$tenant/app/eir/personas/': typeof TenantAppEirPersonasIndexRoute;
  '/$tenant/app/ventures/$ventureId/': typeof TenantAppVenturesVentureIdIndexRoute;
  '/$tenant/app/ventures/$ventureId/coach/$sessionId': typeof TenantAppVenturesVentureIdCoachSessionIdRoute;
  '/$tenant/app/ventures/$ventureId/coach/': typeof TenantAppVenturesVentureIdCoachIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/$tenant/app'
    | '/admin/audit'
    | '/admin/principals'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/'
    | '/$tenant/app/eir'
    | '/$tenant/app/program'
    | '/$tenant/app/'
    | '/$tenant/app/ventures/$ventureId'
    | '/$tenant/app/eir/inbox'
    | '/$tenant/app/eir/reviews'
    | '/$tenant/app/program/escalations'
    | '/$tenant/app/program/portfolio'
    | '/$tenant/app/program/resources'
    | '/$tenant/app/program/ventures'
    | '/$tenant/app/eir/'
    | '/$tenant/app/program/'
    | '/$tenant/app/ventures/'
    | '/$tenant/app/eir/personas/$personaId'
    | '/$tenant/app/ventures/$ventureId/decisions'
    | '/$tenant/app/ventures/$ventureId/documents'
    | '/$tenant/app/ventures/$ventureId/escalations'
    | '/$tenant/app/ventures/$ventureId/evidence'
    | '/$tenant/app/ventures/$ventureId/experiments'
    | '/$tenant/app/ventures/$ventureId/memory'
    | '/$tenant/app/ventures/$ventureId/milestones'
    | '/$tenant/app/ventures/$ventureId/overview'
    | '/$tenant/app/ventures/$ventureId/team'
    | '/$tenant/app/eir/personas/'
    | '/$tenant/app/ventures/$ventureId/'
    | '/$tenant/app/ventures/$ventureId/coach/$sessionId'
    | '/$tenant/app/ventures/$ventureId/coach/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/sign-in'
    | '/admin/audit'
    | '/admin/principals'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin'
    | '/$tenant/app'
    | '/$tenant/app/eir/inbox'
    | '/$tenant/app/eir/reviews'
    | '/$tenant/app/program/escalations'
    | '/$tenant/app/program/portfolio'
    | '/$tenant/app/program/resources'
    | '/$tenant/app/program/ventures'
    | '/$tenant/app/eir'
    | '/$tenant/app/program'
    | '/$tenant/app/ventures'
    | '/$tenant/app/eir/personas/$personaId'
    | '/$tenant/app/ventures/$ventureId/decisions'
    | '/$tenant/app/ventures/$ventureId/documents'
    | '/$tenant/app/ventures/$ventureId/escalations'
    | '/$tenant/app/ventures/$ventureId/evidence'
    | '/$tenant/app/ventures/$ventureId/experiments'
    | '/$tenant/app/ventures/$ventureId/memory'
    | '/$tenant/app/ventures/$ventureId/milestones'
    | '/$tenant/app/ventures/$ventureId/overview'
    | '/$tenant/app/ventures/$ventureId/team'
    | '/$tenant/app/eir/personas'
    | '/$tenant/app/ventures/$ventureId'
    | '/$tenant/app/ventures/$ventureId/coach/$sessionId'
    | '/$tenant/app/ventures/$ventureId/coach';
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sign-in'
    | '/$tenant/app'
    | '/admin/audit'
    | '/admin/principals'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/'
    | '/$tenant/app/eir'
    | '/$tenant/app/program'
    | '/$tenant/app/'
    | '/$tenant/app/ventures/$ventureId'
    | '/$tenant/app/eir/inbox'
    | '/$tenant/app/eir/reviews'
    | '/$tenant/app/program/escalations'
    | '/$tenant/app/program/portfolio'
    | '/$tenant/app/program/resources'
    | '/$tenant/app/program/ventures'
    | '/$tenant/app/eir/'
    | '/$tenant/app/program/'
    | '/$tenant/app/ventures/'
    | '/$tenant/app/eir/personas/$personaId'
    | '/$tenant/app/ventures/$ventureId/decisions'
    | '/$tenant/app/ventures/$ventureId/documents'
    | '/$tenant/app/ventures/$ventureId/escalations'
    | '/$tenant/app/ventures/$ventureId/evidence'
    | '/$tenant/app/ventures/$ventureId/experiments'
    | '/$tenant/app/ventures/$ventureId/memory'
    | '/$tenant/app/ventures/$ventureId/milestones'
    | '/$tenant/app/ventures/$ventureId/overview'
    | '/$tenant/app/ventures/$ventureId/team'
    | '/$tenant/app/eir/personas/'
    | '/$tenant/app/ventures/$ventureId/'
    | '/$tenant/app/ventures/$ventureId/coach/$sessionId'
    | '/$tenant/app/ventures/$ventureId/coach/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRouteRoute: typeof AdminRouteRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  TenantAppRouteRoute: typeof TenantAppRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sign-in': {
      id: '/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$tenant/app': {
      id: '/$tenant/app';
      path: '/$tenant/app';
      fullPath: '/$tenant/app';
      preLoaderRoute: typeof TenantAppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    '/admin/audit': {
      id: '/admin/audit';
      path: '/audit';
      fullPath: '/admin/audit';
      preLoaderRoute: typeof AdminAuditRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    '/admin/principals': {
      id: '/admin/principals';
      path: '/principals';
      fullPath: '/admin/principals';
      preLoaderRoute: typeof AdminPrincipalsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    '/admin/settings': {
      id: '/admin/settings';
      path: '/settings';
      fullPath: '/admin/settings';
      preLoaderRoute: typeof AdminSettingsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    '/admin/usage': {
      id: '/admin/usage';
      path: '/usage';
      fullPath: '/admin/usage';
      preLoaderRoute: typeof AdminUsageRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    '/$tenant/app/': {
      id: '/$tenant/app/';
      path: '/';
      fullPath: '/$tenant/app/';
      preLoaderRoute: typeof TenantAppIndexRouteImport;
      parentRoute: typeof TenantAppRouteRoute;
    };
    '/$tenant/app/eir': {
      id: '/$tenant/app/eir';
      path: '/eir';
      fullPath: '/$tenant/app/eir';
      preLoaderRoute: typeof TenantAppEirRouteRouteImport;
      parentRoute: typeof TenantAppRouteRoute;
    };
    '/$tenant/app/program': {
      id: '/$tenant/app/program';
      path: '/program';
      fullPath: '/$tenant/app/program';
      preLoaderRoute: typeof TenantAppProgramRouteRouteImport;
      parentRoute: typeof TenantAppRouteRoute;
    };
    '/$tenant/app/eir/': {
      id: '/$tenant/app/eir/';
      path: '/';
      fullPath: '/$tenant/app/eir/';
      preLoaderRoute: typeof TenantAppEirIndexRouteImport;
      parentRoute: typeof TenantAppEirRouteRoute;
    };
    '/$tenant/app/eir/inbox': {
      id: '/$tenant/app/eir/inbox';
      path: '/inbox';
      fullPath: '/$tenant/app/eir/inbox';
      preLoaderRoute: typeof TenantAppEirInboxRouteImport;
      parentRoute: typeof TenantAppEirRouteRoute;
    };
    '/$tenant/app/eir/reviews': {
      id: '/$tenant/app/eir/reviews';
      path: '/reviews';
      fullPath: '/$tenant/app/eir/reviews';
      preLoaderRoute: typeof TenantAppEirReviewsRouteImport;
      parentRoute: typeof TenantAppEirRouteRoute;
    };
    '/$tenant/app/program/': {
      id: '/$tenant/app/program/';
      path: '/';
      fullPath: '/$tenant/app/program/';
      preLoaderRoute: typeof TenantAppProgramIndexRouteImport;
      parentRoute: typeof TenantAppProgramRouteRoute;
    };
    '/$tenant/app/program/escalations': {
      id: '/$tenant/app/program/escalations';
      path: '/escalations';
      fullPath: '/$tenant/app/program/escalations';
      preLoaderRoute: typeof TenantAppProgramEscalationsRouteImport;
      parentRoute: typeof TenantAppProgramRouteRoute;
    };
    '/$tenant/app/program/portfolio': {
      id: '/$tenant/app/program/portfolio';
      path: '/portfolio';
      fullPath: '/$tenant/app/program/portfolio';
      preLoaderRoute: typeof TenantAppProgramPortfolioRouteImport;
      parentRoute: typeof TenantAppProgramRouteRoute;
    };
    '/$tenant/app/program/resources': {
      id: '/$tenant/app/program/resources';
      path: '/resources';
      fullPath: '/$tenant/app/program/resources';
      preLoaderRoute: typeof TenantAppProgramResourcesRouteImport;
      parentRoute: typeof TenantAppProgramRouteRoute;
    };
    '/$tenant/app/program/ventures': {
      id: '/$tenant/app/program/ventures';
      path: '/ventures';
      fullPath: '/$tenant/app/program/ventures';
      preLoaderRoute: typeof TenantAppProgramVenturesRouteImport;
      parentRoute: typeof TenantAppProgramRouteRoute;
    };
    '/$tenant/app/ventures/': {
      id: '/$tenant/app/ventures/';
      path: '/ventures';
      fullPath: '/$tenant/app/ventures/';
      preLoaderRoute: typeof TenantAppVenturesIndexRouteImport;
      parentRoute: typeof TenantAppRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId': {
      id: '/$tenant/app/ventures/$ventureId';
      path: '/ventures/$ventureId';
      fullPath: '/$tenant/app/ventures/$ventureId';
      preLoaderRoute: typeof TenantAppVenturesVentureIdRouteRouteImport;
      parentRoute: typeof TenantAppRouteRoute;
    };
    '/$tenant/app/eir/personas/': {
      id: '/$tenant/app/eir/personas/';
      path: '/personas';
      fullPath: '/$tenant/app/eir/personas/';
      preLoaderRoute: typeof TenantAppEirPersonasIndexRouteImport;
      parentRoute: typeof TenantAppEirRouteRoute;
    };
    '/$tenant/app/eir/personas/$personaId': {
      id: '/$tenant/app/eir/personas/$personaId';
      path: '/personas/$personaId';
      fullPath: '/$tenant/app/eir/personas/$personaId';
      preLoaderRoute: typeof TenantAppEirPersonasPersonaIdRouteImport;
      parentRoute: typeof TenantAppEirRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/': {
      id: '/$tenant/app/ventures/$ventureId/';
      path: '/';
      fullPath: '/$tenant/app/ventures/$ventureId/';
      preLoaderRoute: typeof TenantAppVenturesVentureIdIndexRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/decisions': {
      id: '/$tenant/app/ventures/$ventureId/decisions';
      path: '/decisions';
      fullPath: '/$tenant/app/ventures/$ventureId/decisions';
      preLoaderRoute: typeof TenantAppVenturesVentureIdDecisionsRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/documents': {
      id: '/$tenant/app/ventures/$ventureId/documents';
      path: '/documents';
      fullPath: '/$tenant/app/ventures/$ventureId/documents';
      preLoaderRoute: typeof TenantAppVenturesVentureIdDocumentsRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/escalations': {
      id: '/$tenant/app/ventures/$ventureId/escalations';
      path: '/escalations';
      fullPath: '/$tenant/app/ventures/$ventureId/escalations';
      preLoaderRoute: typeof TenantAppVenturesVentureIdEscalationsRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/evidence': {
      id: '/$tenant/app/ventures/$ventureId/evidence';
      path: '/evidence';
      fullPath: '/$tenant/app/ventures/$ventureId/evidence';
      preLoaderRoute: typeof TenantAppVenturesVentureIdEvidenceRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/experiments': {
      id: '/$tenant/app/ventures/$ventureId/experiments';
      path: '/experiments';
      fullPath: '/$tenant/app/ventures/$ventureId/experiments';
      preLoaderRoute: typeof TenantAppVenturesVentureIdExperimentsRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/memory': {
      id: '/$tenant/app/ventures/$ventureId/memory';
      path: '/memory';
      fullPath: '/$tenant/app/ventures/$ventureId/memory';
      preLoaderRoute: typeof TenantAppVenturesVentureIdMemoryRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/milestones': {
      id: '/$tenant/app/ventures/$ventureId/milestones';
      path: '/milestones';
      fullPath: '/$tenant/app/ventures/$ventureId/milestones';
      preLoaderRoute: typeof TenantAppVenturesVentureIdMilestonesRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/overview': {
      id: '/$tenant/app/ventures/$ventureId/overview';
      path: '/overview';
      fullPath: '/$tenant/app/ventures/$ventureId/overview';
      preLoaderRoute: typeof TenantAppVenturesVentureIdOverviewRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/team': {
      id: '/$tenant/app/ventures/$ventureId/team';
      path: '/team';
      fullPath: '/$tenant/app/ventures/$ventureId/team';
      preLoaderRoute: typeof TenantAppVenturesVentureIdTeamRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/coach/': {
      id: '/$tenant/app/ventures/$ventureId/coach/';
      path: '/coach';
      fullPath: '/$tenant/app/ventures/$ventureId/coach/';
      preLoaderRoute: typeof TenantAppVenturesVentureIdCoachIndexRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
    '/$tenant/app/ventures/$ventureId/coach/$sessionId': {
      id: '/$tenant/app/ventures/$ventureId/coach/$sessionId';
      path: '/coach/$sessionId';
      fullPath: '/$tenant/app/ventures/$ventureId/coach/$sessionId';
      preLoaderRoute: typeof TenantAppVenturesVentureIdCoachSessionIdRouteImport;
      parentRoute: typeof TenantAppVenturesVentureIdRouteRoute;
    };
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute;
  AdminPrincipalsRoute: typeof AdminPrincipalsRoute;
  AdminSettingsRoute: typeof AdminSettingsRoute;
  AdminUsageRoute: typeof AdminUsageRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminPrincipalsRoute: AdminPrincipalsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
);

interface TenantAppEirRouteRouteChildren {
  TenantAppEirInboxRoute: typeof TenantAppEirInboxRoute;
  TenantAppEirReviewsRoute: typeof TenantAppEirReviewsRoute;
  TenantAppEirIndexRoute: typeof TenantAppEirIndexRoute;
  TenantAppEirPersonasPersonaIdRoute: typeof TenantAppEirPersonasPersonaIdRoute;
  TenantAppEirPersonasIndexRoute: typeof TenantAppEirPersonasIndexRoute;
}

const TenantAppEirRouteRouteChildren: TenantAppEirRouteRouteChildren = {
  TenantAppEirInboxRoute: TenantAppEirInboxRoute,
  TenantAppEirReviewsRoute: TenantAppEirReviewsRoute,
  TenantAppEirIndexRoute: TenantAppEirIndexRoute,
  TenantAppEirPersonasPersonaIdRoute: TenantAppEirPersonasPersonaIdRoute,
  TenantAppEirPersonasIndexRoute: TenantAppEirPersonasIndexRoute,
};

const TenantAppEirRouteRouteWithChildren =
  TenantAppEirRouteRoute._addFileChildren(TenantAppEirRouteRouteChildren);

interface TenantAppProgramRouteRouteChildren {
  TenantAppProgramEscalationsRoute: typeof TenantAppProgramEscalationsRoute;
  TenantAppProgramPortfolioRoute: typeof TenantAppProgramPortfolioRoute;
  TenantAppProgramResourcesRoute: typeof TenantAppProgramResourcesRoute;
  TenantAppProgramVenturesRoute: typeof TenantAppProgramVenturesRoute;
  TenantAppProgramIndexRoute: typeof TenantAppProgramIndexRoute;
}

const TenantAppProgramRouteRouteChildren: TenantAppProgramRouteRouteChildren = {
  TenantAppProgramEscalationsRoute: TenantAppProgramEscalationsRoute,
  TenantAppProgramPortfolioRoute: TenantAppProgramPortfolioRoute,
  TenantAppProgramResourcesRoute: TenantAppProgramResourcesRoute,
  TenantAppProgramVenturesRoute: TenantAppProgramVenturesRoute,
  TenantAppProgramIndexRoute: TenantAppProgramIndexRoute,
};

const TenantAppProgramRouteRouteWithChildren =
  TenantAppProgramRouteRoute._addFileChildren(
    TenantAppProgramRouteRouteChildren,
  );

interface TenantAppVenturesVentureIdRouteRouteChildren {
  TenantAppVenturesVentureIdDecisionsRoute: typeof TenantAppVenturesVentureIdDecisionsRoute;
  TenantAppVenturesVentureIdDocumentsRoute: typeof TenantAppVenturesVentureIdDocumentsRoute;
  TenantAppVenturesVentureIdEscalationsRoute: typeof TenantAppVenturesVentureIdEscalationsRoute;
  TenantAppVenturesVentureIdEvidenceRoute: typeof TenantAppVenturesVentureIdEvidenceRoute;
  TenantAppVenturesVentureIdExperimentsRoute: typeof TenantAppVenturesVentureIdExperimentsRoute;
  TenantAppVenturesVentureIdMemoryRoute: typeof TenantAppVenturesVentureIdMemoryRoute;
  TenantAppVenturesVentureIdMilestonesRoute: typeof TenantAppVenturesVentureIdMilestonesRoute;
  TenantAppVenturesVentureIdOverviewRoute: typeof TenantAppVenturesVentureIdOverviewRoute;
  TenantAppVenturesVentureIdTeamRoute: typeof TenantAppVenturesVentureIdTeamRoute;
  TenantAppVenturesVentureIdIndexRoute: typeof TenantAppVenturesVentureIdIndexRoute;
  TenantAppVenturesVentureIdCoachSessionIdRoute: typeof TenantAppVenturesVentureIdCoachSessionIdRoute;
  TenantAppVenturesVentureIdCoachIndexRoute: typeof TenantAppVenturesVentureIdCoachIndexRoute;
}

const TenantAppVenturesVentureIdRouteRouteChildren: TenantAppVenturesVentureIdRouteRouteChildren =
  {
    TenantAppVenturesVentureIdDecisionsRoute:
      TenantAppVenturesVentureIdDecisionsRoute,
    TenantAppVenturesVentureIdDocumentsRoute:
      TenantAppVenturesVentureIdDocumentsRoute,
    TenantAppVenturesVentureIdEscalationsRoute:
      TenantAppVenturesVentureIdEscalationsRoute,
    TenantAppVenturesVentureIdEvidenceRoute:
      TenantAppVenturesVentureIdEvidenceRoute,
    TenantAppVenturesVentureIdExperimentsRoute:
      TenantAppVenturesVentureIdExperimentsRoute,
    TenantAppVenturesVentureIdMemoryRoute:
      TenantAppVenturesVentureIdMemoryRoute,
    TenantAppVenturesVentureIdMilestonesRoute:
      TenantAppVenturesVentureIdMilestonesRoute,
    TenantAppVenturesVentureIdOverviewRoute:
      TenantAppVenturesVentureIdOverviewRoute,
    TenantAppVenturesVentureIdTeamRoute: TenantAppVenturesVentureIdTeamRoute,
    TenantAppVenturesVentureIdIndexRoute: TenantAppVenturesVentureIdIndexRoute,
    TenantAppVenturesVentureIdCoachSessionIdRoute:
      TenantAppVenturesVentureIdCoachSessionIdRoute,
    TenantAppVenturesVentureIdCoachIndexRoute:
      TenantAppVenturesVentureIdCoachIndexRoute,
  };

const TenantAppVenturesVentureIdRouteRouteWithChildren =
  TenantAppVenturesVentureIdRouteRoute._addFileChildren(
    TenantAppVenturesVentureIdRouteRouteChildren,
  );

interface TenantAppRouteRouteChildren {
  TenantAppEirRouteRoute: typeof TenantAppEirRouteRouteWithChildren;
  TenantAppProgramRouteRoute: typeof TenantAppProgramRouteRouteWithChildren;
  TenantAppIndexRoute: typeof TenantAppIndexRoute;
  TenantAppVenturesVentureIdRouteRoute: typeof TenantAppVenturesVentureIdRouteRouteWithChildren;
  TenantAppVenturesIndexRoute: typeof TenantAppVenturesIndexRoute;
}

const TenantAppRouteRouteChildren: TenantAppRouteRouteChildren = {
  TenantAppEirRouteRoute: TenantAppEirRouteRouteWithChildren,
  TenantAppProgramRouteRoute: TenantAppProgramRouteRouteWithChildren,
  TenantAppIndexRoute: TenantAppIndexRoute,
  TenantAppVenturesVentureIdRouteRoute:
    TenantAppVenturesVentureIdRouteRouteWithChildren,
  TenantAppVenturesIndexRoute: TenantAppVenturesIndexRoute,
};

const TenantAppRouteRouteWithChildren = TenantAppRouteRoute._addFileChildren(
  TenantAppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  TenantAppRouteRoute: TenantAppRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
