/**
 * Generates src/migrations/bundle.generated.ts from migrations/*.sql so Lambda bundles carry the SQL
 * without filesystem access.
 *
 *   pnpm --filter @foundry/db gen:migrations          # write
 *   pnpm --filter @foundry/db gen:migrations --check  # CI: exit 1 when the bundle is stale
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, '..', '..');
const migrationsDir = join(packageRoot, 'migrations');
const outFile = join(packageRoot, 'src', 'migrations', 'bundle.generated.ts');

export async function renderBundle(): Promise<string> {
  const files = (await readdir(migrationsDir)).filter((f) => /^\d{4}_[a-z0-9_]+\.sql$/.test(f)).sort();
  const entries: string[] = [];
  for (const file of files) {
    const sql = (await readFile(join(migrationsDir, file), 'utf8')).replace(/\r\n/g, '\n');
    const checksum = createHash('sha256').update(sql, 'utf8').digest('hex');
    entries.push(
      [
        '  {',
        `    version: '${file.replace(/\.sql$/, '')}',`,
        `    checksum: '${checksum}',`,
        `    sql: ${JSON.stringify(sql)},`,
        '  },',
      ].join('\n'),
    );
  }
  return [
    '// AUTO-GENERATED by src/scripts/gen-migrations.ts from packages/db/migrations/*.sql — do not edit.',
    "import { type Migration } from './types.js';",
    '',
    'export const MIGRATIONS: readonly Migration[] = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const next = await renderBundle();
  const current = await readFile(outFile, 'utf8').catch(() => '');
  if (check) {
    if (current !== next) {
      console.error('bundle.generated.ts is stale: run `pnpm --filter @foundry/db gen:migrations`');
      process.exit(1);
    }
    return;
  }
  if (current !== next) await writeFile(outFile, next, 'utf8');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err: unknown) => {
    console.error(err instanceof Error ? err.message : 'gen-migrations failed');
    process.exit(1);
  });
}
