import { createHash } from 'node:crypto';

import { authRepo } from '@foundry/db';

import { DomainError } from '../errors.js';
import { type Kit } from '../internal/kit.js';
import { type SessionSigningKey } from './session-token.js';

const KEY_CACHE_MS = 60_000;

interface Cached<T> {
  readonly value: T;
  readonly loadedAt: number;
}

/**
 * Platform keys from `platform_keys` (generated by migration 0001, rotatable), cached for 60 s per
 * container. Key material never leaves this module except as Uint8Array to jose / the IP hasher.
 */
export class PlatformKeyCache {
  #signing: Cached<SessionSigningKey> | null = null;
  #verification: Cached<SessionSigningKey[]> | null = null;
  #ipSalt: Cached<Uint8Array> | null = null;

  constructor(
    private readonly kit: Kit,
    private readonly graceSeconds: number,
  ) {}

  #fresh<T>(entry: Cached<T> | null): entry is Cached<T> {
    return entry !== null && this.kit.now().getTime() - entry.loadedAt < KEY_CACHE_MS;
  }

  async signingKey(): Promise<SessionSigningKey> {
    if (this.#fresh(this.#signing)) return this.#signing.value;
    const key = await this.kit.system((sx) => authRepo.getActivePlatformKey(sx, 'session_signing'), {
      transaction: false,
    });
    if (!key) throw new DomainError('internal', 'Session signing key is not configured');
    const value = { id: key.id, bytes: new Uint8Array(Buffer.from(key.keyBase64, 'base64')) };
    this.#signing = { value, loadedAt: this.kit.now().getTime() };
    return value;
  }

  async verificationKeys(): Promise<SessionSigningKey[]> {
    if (this.#fresh(this.#verification)) return this.#verification.value;
    const keys = await this.kit.system(
      (sx) =>
        authRepo.listVerificationKeys(sx, { purpose: 'session_signing', graceSeconds: this.graceSeconds }),
      { transaction: false },
    );
    const value = keys.map((k) => ({ id: k.id, bytes: new Uint8Array(Buffer.from(k.keyBase64, 'base64')) }));
    this.#verification = { value, loadedAt: this.kit.now().getTime() };
    return value;
  }

  async ipSalt(): Promise<Uint8Array> {
    if (this.#fresh(this.#ipSalt)) return this.#ipSalt.value;
    const key = await this.kit.system((sx) => authRepo.getActivePlatformKey(sx, 'ip_hash_salt'), {
      transaction: false,
    });
    if (!key) throw new DomainError('internal', 'IP hash salt is not configured');
    const value = new Uint8Array(Buffer.from(key.keyBase64, 'base64'));
    this.#ipSalt = { value, loadedAt: this.kit.now().getTime() };
    return value;
  }

  /** Drops cached keys (after a rotation in this container). */
  clear(): void {
    this.#signing = null;
    this.#verification = null;
    this.#ipSalt = null;
  }
}

/**
 * Salted SHA-256 of a viewer attribute (IP address or user agent). Raw IPs are never stored or logged;
 * `auth_attempts.subject_hash` holds this value.
 */
export function hashViewerAttribute(
  salt: Uint8Array,
  kind: 'ip' | 'ua',
  value: string | null | undefined,
): string {
  const normalized = (value ?? '').trim().toLowerCase().slice(0, 512) || 'unknown';
  return createHash('sha256')
    .update(salt)
    .update(`\u0000${kind}\u0000`)
    .update(normalized, 'utf8')
    .digest('hex');
}
